# Generated by Django 5.0.1 on 2024-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('personal_email', models.CharField(max_length=50)),
                ('professional_email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('educational_background', models.CharField(max_length=200)),
                ('job_objective', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('status_type', models.CharField(max_length=50)),
                ('internship', models.CharField(max_length=50)),
                ('last_position', models.CharField(max_length=50)),
                ('present_position', models.CharField(max_length=50)),
                ('constract_start_date', models.DateField()),
                ('contract_expiration_date', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('changes', models.CharField(max_length=50)),
                ('financial_bonuses', models.CharField(max_length=50)),
                ('date1', models.DateTimeField()),
                ('other_bonuses', models.CharField(max_length=50)),
                ('date2', models.DateTimeField()),
            ],
        ),
    ]
