# Generated by Django 5.0.6 on 2024-05-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_contract_contract_contract_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employees.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='employees.employee'),
            preserve_default=False,
        ),
    ]
